const constants = {
    ADD_PRODUCTITEM: "ADD_PRODUCTITEM",
    ADD_MATERIALITEM: "ADD_MATERIALITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    CALCULATION_RESULT: "CALCULATION_RESULT",
    CLEAR_RESULT: "CLEAR_RESULT"
}

export default constants